# Generated by Django 2.1.1 on 2018-09-21 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=128, verbose_name='书名')),
                ('book_author', models.CharField(max_length=32, verbose_name='作者')),
                ('book_desc', models.TextField(verbose_name='描述')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('upload_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_books', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '图书',
                'verbose_name_plural': '图书',
                'ordering': ('-created',),
            },
        ),
    ]
