# Generated by Django 2.1.1 on 2018-11-12 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='书名')),
                ('cover_picture', models.ImageField(default='image/default.jpg', upload_to='image/book/picture', verbose_name='封面图')),
                ('desc', models.TextField(verbose_name='简介')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='resource/pdf')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '图书',
                'verbose_name_plural': '图书',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='分类名')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'ordering': ('-name',),
            },
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_books', to='books.Category', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='book',
            name='upload_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_books', to=settings.AUTH_USER_MODEL, verbose_name='上传者'),
        ),
    ]
