# Generated by Django 2.1.1 on 2018-09-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_picture',
            field=models.ImageField(default='image/default.jpg', upload_to='image/book/picture', verbose_name='封面图'),
        ),
    ]
