# Generated by Django 2.1.1 on 2018-09-22 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20180921_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_name',
            new_name='name',
        ),
    ]
