# Generated by Django 2.1.1 on 2018-09-22 14:35

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20180922_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_picture',
            field=imagekit.models.fields.ProcessedImageField(upload_to='image/book/picture', verbose_name='封面图'),
        ),
    ]
