# Generated by Django 2.1.1 on 2018-09-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20180922_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_picture',
            field=models.ImageField(default='image/default.jpg', upload_to='image/book/picture', verbose_name='封面图'),
        ),
    ]
