# Generated by Django 2.1.1 on 2018-09-23 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20180922_1733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-name',), 'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
    ]
