# Generated by Django 2.1.1 on 2018-09-23 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='like',
            new_name='like_user',
        ),
    ]
