# Generated by Django 2.1.1 on 2018-09-23 16:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20180923_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='like_user',
            field=models.ManyToManyField(blank=True, related_name='like_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
