# Generated by Django 2.1.1 on 2018-09-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20180923_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '书评', 'verbose_name_plural': '书评'},
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default=None, verbose_name='评论内容'),
        ),
    ]
